- name: Instalar HAProxy
  hosts: haproxy
  become: yes
  tasks:
    - name: Actualizar cache apt
      apt:
        update_cache: yes

    - name: Instalar HAProxy
      apt:
        name: haproxy
        state: present

    - name: Habilitar e iniciar HAProxy
      systemd:
        name: haproxy
        enabled: yes
        state: started
